# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 20:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20160302_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moon',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z \\.-]*$', 'Only alphanumeric characters, hyphens, periods, and spaces are allowed')]),
        ),
        migrations.AlterField(
            model_name='planet',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z \\.-]*$', 'Only alphanumeric characters, hyphens, periods, and spaces are allowed')]),
        ),
        migrations.AlterField(
            model_name='planetarysystem',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z \\.-]*$', 'Only alphanumeric characters, hyphens, periods, and spaces are allowed')]),
        ),
        migrations.AlterField(
            model_name='star',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z \\.-]*$', 'Only alphanumeric characters, hyphens, periods, and spaces are allowed')]),
        ),
        migrations.AlterUniqueTogether(
            name='moon',
            unique_together=set([('creator', 'planet', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='planet',
            unique_together=set([('creator', 'star', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='planetarysystem',
            unique_together=set([('creator', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='star',
            unique_together=set([('creator', 'planetarysystem', 'name')]),
        ),
    ]
