# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 18:38
from __future__ import unicode_literals

import colorfield2.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20160308_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='moon',
            name='color',
            field=colorfield2.fields.ColorField(default='#999', max_length=10),
        ),
        migrations.AddField(
            model_name='planet',
            name='color',
            field=colorfield2.fields.ColorField(default='#abcdef', max_length=10),
        ),
    ]
