# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20160316_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='planetarysystem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.PlanetarySystem'),
        ),
    ]
