# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 05:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0002_auto_20160229_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='star',
            old_name='solar_system',
            new_name='solarsystem',
        ),
    ]
