# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0003_auto_20160229_2348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moon',
            options={'ordering': ['distance']},
        ),
        migrations.AlterModelOptions(
            name='planet',
            options={'ordering': ['distance']},
        ),
        migrations.AlterField(
            model_name='moon',
            name='distance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='moon',
            name='radius',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='planet',
            name='distance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='planet',
            name='radius',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='star',
            name='radius',
            field=models.IntegerField(),
        ),
    ]
