# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moon',
            name='orbit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='planet',
            name='orbit',
            field=models.FloatField(),
        ),
    ]
