# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20160308_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='planetarysystem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.PlanetarySystem'),
        ),
        migrations.AlterUniqueTogether(
            name='planet',
            unique_together=set([('creator', 'planetarysystem', 'name')]),
        ),
        migrations.RemoveField(
            model_name='planet',
            name='star',
        ),
    ]
