# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20160317_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='radius',
        ),
        migrations.AddField(
            model_name='star',
            name='spectrum',
            field=models.CharField(choices=[('O', 'O'), ('B', 'B'), ('A', 'A'), ('F', 'F'), ('G', 'G'), ('K', 'K'), ('M', 'M')], default='G', max_length=1),
        ),
        migrations.AddField(
            model_name='star',
            name='subspectrum',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=2),
        ),
    ]
