# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 03:59
from __future__ import unicode_literals

import colorfield2.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20160319_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moon',
            name='color',
            field=colorfield2.fields.HexColorField(default='#abcdef', max_length=10),
        ),
    ]
