# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('radius', models.FloatField()),
                ('distance', models.FloatField()),
                ('day_length', models.IntegerField()),
                ('orbit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('radius', models.FloatField()),
                ('distance', models.FloatField()),
                ('day_length', models.IntegerField()),
                ('orbit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SolarSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('radius', models.FloatField()),
                ('solar_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solar.SolarSystem')),
            ],
        ),
        migrations.AddField(
            model_name='planet',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solar.Star'),
        ),
        migrations.AddField(
            model_name='moon',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solar.Planet'),
        ),
    ]
